### ISSUE TITLE
[Doc] User guide to upgrade Linux Kernel to meet eBPF requirements.

### ISSUE THREAD

**Issue by yqlbu** [v2rayA/dae#20]
## Summary

Consider adding documentation support to provide end-users with a step-by-step guide to upgrade the Linux Kernel on the host to the minimum version (v5.8) so as to meet the environment requirement for Dae.

**Comment by yqlbu** [comment]
Ideally, we may consider adding an additional folder, namely `./docs` to include all additional docs for any kind of support.

**Comment by mzz2017** [comment]
@yqlbu LGTM. Thanks for your help.

**Comment by yqlbu** [comment]
Resolved in #21.
