### ISSUE TITLE
FATA[0002] BindWan: eth0: cannot add clsact qdisc: no such file or directory

### ISSUE THREAD

**Issue by kunish** [v2rayA/dae#7]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/17328586/216995363-be5717ea-48a7-4088-9ed9-a731f65615f6.png">

**Comment by mzz2017** [comment]
@kunish What is your kernel version?

**Comment by mzz2017** [comment]
@kunish uname -r

**Comment by kunish** [comment]
@mzz2017 

```sh
uname -r

6.1.9-arch1-1
```

**Comment by MarksonHon** [comment]
`uname -a`

Show your Linux kernel version

**Comment by mzz2017** [comment]
@kunish sudo tc qdisc add dev eth0 clsact

**Comment by kunish** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/17328586/216996939-90d17b49-f680-4525-82f7-1b6b1b0192cb.png">

**Comment by mzz2017** [comment]
@kunish clsact should be added in kernel 4.5. What is your distribution？

**Comment by kunish** [comment]
@mzz2017 just a plain archlinux installation but ontop of virtualization system

**Comment by kunish** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/17328586/216998351-c85b0900-1e04-4cac-82cc-63a905da59db.png">

Just think it as a QEMU machine

**Comment by kunish** [comment]
Long story short, it's a problem on my side.

After a system reboot, I created a brand new QMEU instance, it runs fine now. Maybe something related to kernel module that has changed since I first created this virtual machine.

**Comment by mzz2017** [comment]
@kunish Congratulations!
