### ISSUE TITLE
编译包ethtool的checksum错误，是否需要更新下go.sum的sum?

### ISSUE THREAD

**Issue by zcluo** [v2rayA/dae#9]
verifying github.com/safchain/ethtool@v0.2.0: checksum mismatch
        downloaded: h1:tjsEsesUSlGdnUAAiIaEvk/YEycwk0k3Q6/q77qGpBI=
        go.sum:     h1:dILxMBqDnQfX192cCAPjZr9v2IgVXeElHPy435Z/IdE=

SECURITY ERROR

**Comment by MarksonHon** [comment]
手动从golang官网安装go，部分发行版的二进制存在问题
